### PR TITLE
Parse expressions with nested license names and spaces

### PR DESCRIPTION
**Pull request by pombredanne**
This is a fix for the #29 bug

### CODE REVIEW

**Comment by pombredanne** [comment]
@tdruez this should be fixing #29 and still supports parsing license symbols with spaces (such as names, etc) ass before. Your review is welcomed!

**Comment by pombredanne** [comment]
Note that the changes are quite extensive because of some renaming for clarity.
The key changes are:
1. Licensing.tokenize accepts a "simple" argument to use either a simple or and advanced tokenizer explicitly (this was implied before)

2. The automaton-based tokenizer that can handle spaces and other license symbols weirdness  now works using sequence of words (as separated by spaces or parens) as opposed to use characters sequences before. This also to handle the #29 issues of a license name containing another license name properly (when one of the two is not for a known symbol)  

3. More tests have been added for various corner cases and parsing has been improved


As a side note, the travis config has been fixed such that tests now run OK on all OSes and Python versions

**Comment by tdruez** [comment]
@pombredanne the changes looks good. Thanks for all the extra unit tests.
My only concern is about the `if TRACE:` placed a bit everywhere. 
This seems to duplicate the logic of the logging setup module.

**Comment by pombredanne** [comment]
@tdruez in reply to:
> My only concern is about the if TRACE: placed a bit everywhere.
> This seems to duplicate the logic of the logging setup module. Minor in any cases.

We do not need this tracing anymore ... so let me remove this.
The reason why if commonly use a `TRACE` flag is that in some cases collecting the arguments to a debug `logger` call is more expensive than calling the logger itself... hence the flag

**Comment by pombredanne** [comment]
@tdruez in reply to:
> My only concern is about the if TRACE: placed a bit everywhere.
> This seems to duplicate the logic of the logging setup module. Minor in any cases.

We do not need this tracing anymore ... so let me remove this.
The reason why if commonly use a `TRACE` flag is that in some cases collecting the arguments to a debug `logger` call is more expensive than calling the logger itself... hence the flag 

I pushed a  version without this and will merge shortly

**Pull request merged**
